name: Install Dependencies

on:
  push:
    branches:
      - main
      - develop  
  pull_request:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 
    - name: Set up Python 3.x  
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: dependencies installation
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify installation 
      run: |
        pip list  # List installed packages
